version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      github-actions-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directories:
      - "/web"
      - "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        group-by: "dependency-name"

  - package-ecosystem: "pip"
    directory: "/ai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      python-minor-patch:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
