export type OpenApiSchema = Record<string, unknown>;

const text = { type: 'string' };
const integer = { type: 'integer' };
const number = { type: 'number' };
const boolean = { type: 'boolean' };
const dateTime = { type: 'string', format: 'date-time' };

const ref = (name: string): OpenApiSchema => ({
  $ref: `#/components/schemas/${name}`,
});
const array = (items: OpenApiSchema): OpenApiSchema => ({
  type: 'array',
  items,
});
const nullable = (schema: OpenApiSchema): OpenApiSchema => ({
  ...schema,
  nullable: true,
});
const nullableRef = (name: string): OpenApiSchema => ({
  type: 'object',
  nullable: true,
  allOf: [ref(name)],
});
const object = (
  required: string[],
  properties: Record<string, OpenApiSchema>,
  additionalProperties?: boolean,
): OpenApiSchema => ({
  type: 'object',
  required,
  properties,
  ...(additionalProperties === undefined ? {} : { additionalProperties }),
});

export const domainOpenApiSchemas: Record<string, OpenApiSchema> = {
  CourseStepResponse: object(
    ['id', 'position', 'sourcePostId', 'snapshot', 'ownerLearningState'],
    {
      id: text,
      position: integer,
      sourcePostId: nullable(integer),
      snapshot: ref('CourseStepSnapshotDto'),
      ownerLearningState: ref('OwnerLearningStateDto'),
    },
  ),
  CourseFeedbackResponse: object(
    ['id', 'authorId', 'authorName', 'rating', 'body', 'createdAt'],
    {
      id: integer,
      authorId: integer,
      authorName: text,
      rating: integer,
      body: text,
      createdAt: dateTime,
    },
  ),
  PublicCourseFeedbackResponse: object(
    ['id', 'authorName', 'rating', 'body', 'createdAt'],
    {
      id: integer,
      authorName: text,
      rating: integer,
      body: text,
      createdAt: dateTime,
    },
  ),
  OwnerCourseResponse: object(
    [
      'id',
      'ownerId',
      'title',
      'description',
      'visibility',
      'status',
      'version',
      'createdAt',
      'updatedAt',
      'publishedAt',
      'archivedAt',
      'steps',
      'feedback',
    ],
    {
      id: integer,
      ownerId: integer,
      title: text,
      description: text,
      visibility: { type: 'string', enum: ['private', 'public'] },
      status: { type: 'string', enum: ['draft', 'published', 'archived'] },
      version: integer,
      createdAt: dateTime,
      updatedAt: dateTime,
      publishedAt: nullable(dateTime),
      archivedAt: nullable(dateTime),
      steps: array(ref('CourseStepResponse')),
      feedback: array(ref('CourseFeedbackResponse')),
    },
  ),
  PublicCourseStepResponse: object(['id', 'position', 'snapshot'], {
    id: text,
    position: integer,
    snapshot: ref('CourseStepSnapshotDto'),
  }),
  PublicCourseResponse: object(
    [
      'id',
      'title',
      'description',
      'visibility',
      'status',
      'version',
      'createdAt',
      'updatedAt',
      'publishedAt',
      'steps',
      'feedback',
    ],
    {
      id: integer,
      title: text,
      description: text,
      visibility: { type: 'string', enum: ['public'] },
      status: { type: 'string', enum: ['published'] },
      version: integer,
      createdAt: dateTime,
      updatedAt: dateTime,
      publishedAt: dateTime,
      steps: array(ref('PublicCourseStepResponse')),
      feedback: array(ref('PublicCourseFeedbackResponse')),
    },
  ),
  OwnerCoursePageResponse: object(['items', 'nextCursor'], {
    items: array(ref('OwnerCourseResponse')),
    nextCursor: nullable(text),
  }),
  PublicCoursePageResponse: object(['items', 'nextCursor'], {
    items: array(ref('PublicCourseResponse')),
    nextCursor: nullable(text),
  }),

  AgentBudgetsResponse: object(
    [
      'wallTimeBudgetMs',
      'toolCallBudget',
      'tokenBudget',
      'estimatedCostBudgetUsd',
    ],
    {
      wallTimeBudgetMs: integer,
      toolCallBudget: integer,
      tokenBudget: integer,
      estimatedCostBudgetUsd: number,
    },
  ),
  AgentUsageResponse: object(['toolCalls', 'tokens', 'estimatedCostUsd'], {
    toolCalls: integer,
    tokens: integer,
    estimatedCostUsd: number,
  }),
  ProposedCourseStepResponse: object(
    [
      'position',
      'title',
      'videoUrl',
      'thumbnailUrl',
      'channelName',
      'sourcePostId',
      'evidenceSourceUrl',
      'evidenceTimestampSeconds',
      'evidenceConfidence',
      'status',
      'durationSeconds',
    ],
    {
      position: integer,
      title: text,
      videoUrl: { type: 'string', format: 'uri' },
      thumbnailUrl: { type: 'string', format: 'uri' },
      channelName: text,
      sourcePostId: nullable(integer),
      evidenceSourceUrl: { type: 'string', format: 'uri' },
      evidenceTimestampSeconds: integer,
      evidenceConfidence: number,
      status: { type: 'string', enum: ['ready', 'needs_replacement'] },
      durationSeconds: integer,
    },
  ),
  AgentRunAttemptResponse: object(
    [
      'id',
      'attemptNumber',
      'state',
      'queuedAt',
      'startedAt',
      'finishedAt',
      'failureCode',
      'failureMessage',
      'usage',
    ],
    {
      id: { type: 'string', format: 'uuid' },
      attemptNumber: integer,
      state: {
        type: 'string',
        enum: ['queued', 'running', 'completed', 'failed', 'cancelled'],
      },
      queuedAt: dateTime,
      startedAt: nullable(dateTime),
      finishedAt: nullable(dateTime),
      failureCode: nullable(text),
      failureMessage: nullable(text),
      usage: ref('AgentUsageResponse'),
    },
  ),
  AgentRunTransitionResponse: object(
    [
      'fromState',
      'toState',
      'runVersion',
      'reasonCode',
      'actorKind',
      'occurredAt',
    ],
    {
      fromState: nullable(text),
      toState: text,
      runVersion: integer,
      reasonCode: nullable(text),
      actorKind: { type: 'string', enum: ['user', 'worker', 'system'] },
      occurredAt: dateTime,
    },
  ),
  AgentRunResponse: object(
    [
      'id',
      'ownerId',
      'courseId',
      'state',
      'version',
      'input',
      'budgets',
      'usage',
      'queuedAt',
      'startedAt',
      'finishedAt',
      'updatedAt',
      'cancellationRequestedAt',
      'failureCode',
      'attempts',
      'transitions',
      'proposedSteps',
    ],
    {
      id: { type: 'string', format: 'uuid' },
      ownerId: integer,
      courseId: nullable(integer),
      state: {
        type: 'string',
        enum: [
          'queued',
          'running',
          'awaiting_approval',
          'approved',
          'completed',
          'failed',
          'cancelled',
        ],
      },
      version: integer,
      input: { type: 'object', additionalProperties: true },
      budgets: ref('AgentBudgetsResponse'),
      usage: ref('AgentUsageResponse'),
      queuedAt: dateTime,
      startedAt: nullable(dateTime),
      finishedAt: nullable(dateTime),
      updatedAt: dateTime,
      cancellationRequestedAt: nullable(dateTime),
      failureCode: nullable(text),
      attempts: array(ref('AgentRunAttemptResponse')),
      transitions: array(ref('AgentRunTransitionResponse')),
      proposedSteps: array(ref('ProposedCourseStepResponse')),
    },
  ),
  WatchedRangeResponse: object(['start', 'end'], {
    start: number,
    end: number,
  }),
  LearningProgressResponse: object(
    [
      'courseStepId',
      'watchedRanges',
      'lastPositionSeconds',
      'watchedCoverage',
      'bestQuizScore',
      'completedAt',
      'version',
    ],
    {
      courseStepId: text,
      watchedRanges: array(ref('WatchedRangeResponse')),
      lastPositionSeconds: number,
      watchedCoverage: number,
      bestQuizScore: nullable(number),
      completedAt: nullable(dateTime),
      version: integer,
    },
  ),
  QuizQuestionResponse: object(
    [
      'id',
      'position',
      'prompt',
      'choices',
      'sourceUrl',
      'sourceStartSeconds',
      'sourceEndSeconds',
    ],
    {
      id: { type: 'string', format: 'uuid' },
      position: integer,
      prompt: text,
      choices: array(text),
      sourceUrl: { type: 'string', format: 'uri' },
      sourceStartSeconds: number,
      sourceEndSeconds: number,
    },
  ),
  QuizResponse: object(
    [
      'id',
      'courseStepId',
      'version',
      'schemaVersion',
      'maxAttempts',
      'questions',
    ],
    {
      id: { type: 'string', format: 'uuid' },
      courseStepId: text,
      version: integer,
      schemaVersion: integer,
      maxAttempts: integer,
      questions: array(ref('QuizQuestionResponse')),
    },
  ),
  QuizAttemptAnswerResponse: object(
    [
      'questionId',
      'selectedChoiceIndex',
      'correct',
      'correctChoiceIndex',
      'explanation',
    ],
    {
      questionId: { type: 'string', format: 'uuid' },
      selectedChoiceIndex: integer,
      correct: boolean,
      correctChoiceIndex: integer,
      explanation: text,
    },
  ),
  QuizAttemptResponse: object(
    [
      'id',
      'quizId',
      'attemptNumber',
      'score',
      'submittedAt',
      'answers',
      'bestScore',
      'latestScore',
      'attemptsRemaining',
    ],
    {
      id: { type: 'string', format: 'uuid' },
      quizId: { type: 'string', format: 'uuid' },
      attemptNumber: integer,
      score: number,
      submittedAt: dateTime,
      answers: array(ref('QuizAttemptAnswerResponse')),
      bestScore: number,
      latestScore: number,
      attemptsRemaining: integer,
    },
  ),

  CommentResponse: object(
    ['id', 'postId', 'authorId', 'authorName', 'body', 'createdAt'],
    {
      id: integer,
      postId: integer,
      authorId: integer,
      authorName: text,
      body: text,
      createdAt: dateTime,
    },
  ),
  StudyPostResponse: object(
    [
      'id',
      'authorId',
      'authorName',
      'title',
      'videoUrl',
      'thumbnailUrl',
      'channelName',
      'summary',
      'translatedNotes',
      'tags',
      'comments',
      'createdAt',
      'updatedAt',
    ],
    {
      id: integer,
      authorId: integer,
      authorName: text,
      title: text,
      videoUrl: { type: 'string', format: 'uri' },
      thumbnailUrl: text,
      channelName: text,
      summary: text,
      translatedNotes: text,
      tags: array(text),
      comments: array(ref('CommentResponse')),
      createdAt: dateTime,
      updatedAt: dateTime,
    },
  ),
  PaginatedPostsResponse: object(['items', 'total', 'page', 'pageSize'], {
    items: array(ref('StudyPostResponse')),
    total: integer,
    page: integer,
    pageSize: integer,
  }),
  PlaylistFeedbackResponse: object(
    [
      'id',
      'playlistId',
      'authorId',
      'authorName',
      'rating',
      'body',
      'createdAt',
    ],
    {
      id: integer,
      playlistId: integer,
      authorId: integer,
      authorName: text,
      rating: integer,
      body: text,
      createdAt: dateTime,
    },
  ),
  PlaylistResponse: object(
    [
      'id',
      'ownerId',
      'title',
      'description',
      'postIds',
      'feedback',
      'createdAt',
    ],
    {
      id: integer,
      ownerId: integer,
      title: text,
      description: text,
      postIds: array(integer),
      feedback: array(ref('PlaylistFeedbackResponse')),
      createdAt: dateTime,
    },
  ),
  VideoAssetSegmentResponse: object(['start', 'end', 'text'], {
    start: number,
    end: number,
    text,
  }),
  VideoAssetSummarySectionResponse: object(['label', 'body'], {
    label: text,
    body: text,
  }),
  VideoAssetResponse: object(
    [
      'id',
      'postId',
      'videoId',
      'videoUrl',
      'language',
      'sourceLanguage',
      'status',
      'sourceCaptionStatus',
      'translationStatus',
      'summaryStatus',
      'sourceSegments',
      'translatedSegments',
      'summarySections',
      'transcriptBody',
      'errorMessage',
      'createdAt',
      'updatedAt',
    ],
    {
      id: integer,
      postId: integer,
      videoId: text,
      videoUrl: { type: 'string', format: 'uri' },
      language: text,
      sourceLanguage: text,
      status: {
        type: 'string',
        enum: ['pending', 'processing', 'ready', 'partial', 'failed'],
      },
      sourceCaptionStatus: {
        type: 'string',
        enum: ['pending', 'ready', 'partial', 'failed'],
      },
      translationStatus: {
        type: 'string',
        enum: ['pending', 'ready', 'partial', 'failed'],
      },
      summaryStatus: {
        type: 'string',
        enum: ['pending', 'ready', 'partial', 'failed'],
      },
      sourceSegments: array(ref('VideoAssetSegmentResponse')),
      translatedSegments: array(ref('VideoAssetSegmentResponse')),
      summarySections: array(ref('VideoAssetSummarySectionResponse')),
      transcriptBody: text,
      errorMessage: text,
      createdAt: dateTime,
      updatedAt: dateTime,
    },
  ),

  RetrievalCitationResponse: object(['sourceUrl', 'timestampSeconds'], {
    sourceUrl: { type: 'string', format: 'uri' },
    timestampSeconds: nullable(number),
  }),
  RetrievalSourceResponse: object(
    [
      'sourceKind',
      'sourceId',
      'visibility',
      'title',
      'content',
      'score',
      'citation',
    ],
    {
      sourceKind: { type: 'string', enum: ['post', 'course_step'] },
      sourceId: text,
      visibility: { type: 'string', enum: ['private', 'public'] },
      title: text,
      content: text,
      score: number,
      citation: ref('RetrievalCitationResponse'),
    },
  ),
  AiRecommendationResponse: object(
    ['mode', 'query', 'answer', 'relatedPosts', 'sources'],
    {
      mode: text,
      query: text,
      answer: text,
      relatedPosts: array(
        object(['id', 'title', 'summary', 'videoUrl', 'score', 'citation'], {
          id: integer,
          title: text,
          summary: text,
          videoUrl: { type: 'string', format: 'uri' },
          score: number,
          citation: ref('RetrievalCitationResponse'),
        }),
      ),
      sources: array(ref('RetrievalSourceResponse')),
      embedding: object(['provider', 'dimensions'], {
        provider: text,
        dimensions: integer,
      }),
      retrieval: object(['lexical', 'semantic', 'fusion'], {
        lexical: text,
        semantic: text,
        fusion: text,
      }),
      usage: object(['model', 'totalTokens', 'estimatedCostUsd'], {
        model: text,
        totalTokens: integer,
        estimatedCostUsd: number,
      }),
    },
  ),
  YoutubeLookupResponse: object(['jsonrpc', 'id', 'result'], {
    jsonrpc: { type: 'string', enum: ['2.0'] },
    id: text,
    result: object(
      [
        'provider',
        'title',
        'channel',
        'thumbnailUrl',
        'sourceUrl',
        'durationLabel',
        'summary',
        'videos',
      ],
      {
        provider: text,
        title: text,
        channel: text,
        thumbnailUrl: text,
        sourceUrl: text,
        durationLabel: text,
        summary: text,
        videos: array(ref('YoutubeVideoResponse')),
      },
      true,
    ),
  }),
  YoutubeVideoResponse: object(
    [
      'provider',
      'videoId',
      'title',
      'channel',
      'thumbnailUrl',
      'sourceUrl',
      'durationLabel',
      'summary',
    ],
    {
      provider: text,
      videoId: text,
      title: text,
      channel: text,
      thumbnailUrl: text,
      sourceUrl: text,
      durationLabel: text,
      summary: text,
    },
    true,
  ),
  YoutubeCaptionsResponse: object(
    [
      'mode',
      'provider',
      'videoId',
      'language',
      'sourceLanguage',
      'translated',
      'segments',
      'message',
    ],
    {
      mode: text,
      provider: text,
      videoId: text,
      language: text,
      sourceLanguage: text,
      translated: boolean,
      segments: array(ref('VideoAssetSegmentResponse')),
      sourceSegments: array(ref('VideoAssetSegmentResponse')),
      translatedSegments: array(ref('VideoAssetSegmentResponse')),
      message: text,
    },
    true,
  ),
  YoutubeSummaryResponse: object(
    ['mode', 'provider', 'videoId', 'language', 'sections', 'message'],
    {
      mode: text,
      provider: text,
      videoId: text,
      language: text,
      sections: array(ref('VideoAssetSummarySectionResponse')),
      message: text,
    },
    true,
  ),
  StudyPlanResponse: object(
    ['mode', 'goal', 'recommendations', 'rationale', 'trace'],
    {
      mode: text,
      goal: text,
      recommendations: array({ type: 'object', additionalProperties: true }),
      rationale: text,
      trace: array({ type: 'object', additionalProperties: true }),
    },
    true,
  ),
};

export const domainResponseSchemas: Record<string, OpenApiSchema> = {
  AiController_plan: ref('StudyPlanResponse'),
  AiController_lookupYoutube: ref('YoutubeLookupResponse'),
  AiController_recommend: ref('AiRecommendationResponse'),
  AiController_captions: ref('YoutubeCaptionsResponse'),
  AiController_summary: ref('YoutubeSummaryResponse'),

  CourseController_list: ref('OwnerCoursePageResponse'),
  CourseController_create: ref('OwnerCourseResponse'),
  CourseController_get: ref('OwnerCourseResponse'),
  CourseController_update: ref('OwnerCourseResponse'),
  CourseController_archive: ref('OwnerCourseResponse'),
  CourseController_feedback: ref('PublicCourseFeedbackResponse'),
  CourseController_publish: ref('OwnerCourseResponse'),
  CourseController_replaceSteps: ref('OwnerCourseResponse'),
  PublicCourseController_list: ref('PublicCoursePageResponse'),
  PublicCourseController_get: ref('PublicCourseResponse'),

  LearningController_createRun: ref('AgentRunResponse'),
  LearningController_getRun: ref('AgentRunResponse'),
  LearningController_approveRun: ref('AgentRunResponse'),
  LearningController_cancelRun: ref('AgentRunResponse'),
  LearningController_retryRun: ref('AgentRunResponse'),
  LearningController_getProgress: ref('LearningProgressResponse'),
  LearningController_recordProgress: ref('LearningProgressResponse'),
  LearningController_getQuiz: ref('QuizResponse'),
  LearningController_submitQuiz: ref('QuizAttemptResponse'),
  LearningController_listQuizAttempts: array(ref('QuizAttemptResponse')),

  StudyBoardController_listPublicPosts: ref('PaginatedPostsResponse'),
  StudyBoardController_listPosts: ref('PaginatedPostsResponse'),
  StudyBoardController_createPost: ref('StudyPostResponse'),
  StudyBoardController_getPost: ref('StudyPostResponse'),
  StudyBoardController_updatePost: ref('StudyPostResponse'),
  StudyBoardController_addComment: ref('CommentResponse'),
  StudyBoardController_listPlaylists: array(ref('PlaylistResponse')),
  StudyBoardController_createPlaylist: ref('PlaylistResponse'),
  StudyBoardController_updatePlaylist: ref('PlaylistResponse'),
  StudyBoardController_addPlaylistItem: ref('PlaylistResponse'),
  StudyBoardController_addPlaylistFeedback: ref('PlaylistFeedbackResponse'),

  VideoAssetController_getAsset: ref('VideoAssetResponse'),
  VideoAssetController_prepare: nullableRef('VideoAssetResponse'),
};
