export const PRESERVED_APPLICATION_TABLES = [
  'learning_cutover_authority',
  'learning_cutover_runs',
  'pgmigrations',
  'stt_provider_approvals',
] as const;

export const RESET_APPLICATION_TABLES = [
  'adaptive_quiz_answers',
  'adaptive_quiz_attempts',
  'adaptive_quiz_evidence',
  'adaptive_quiz_loops',
  'adaptive_quiz_questions',
  'adaptive_quiz_review_proposals',
  'agent_run_attempts',
  'agent_run_state_transitions',
  'agent_run_work_items',
  'agent_runs',
  'agent_tool_calls',
  'auth_rate_limits',
  'caption_artifact_segments',
  'caption_artifacts',
  'caption_generation_states',
  'caption_work_failures',
  'comments',
  'course_backfill_audits',
  'course_feedback',
  'course_steps',
  'courses',
  'google_auth_attempts',
  'learning_context_summaries',
  'learning_cutover_source_changes',
  'learning_items',
  'learning_notes',
  'learning_progress',
  'learning_progress_events',
  'learning_proposals',
  'learning_retrieval_context_snapshots',
  'legacy_learning_context_mappings',
  'pending_registrations',
  'playlist_feedback',
  'playlist_items',
  'playlists',
  'post_embeddings',
  'post_tags',
  'posts',
  'provider_subscription_reservations',
  'provider_work_reservations',
  'quiz_answers',
  'quiz_attempts',
  'quiz_questions',
  'quizzes',
  'retrieval_embedding_cache',
  'retrieval_embeddings',
  'sessions',
  'study_contexts',
  'tags',
  'users',
  'video_assets',
  'video_sources',
  'verification_email_outbox',
  'work_dead_letters',
  'work_job_claims',
  'work_job_results',
  'work_outbox_events',
  'work_replay_audits',
] as const;

export type ResetApplicationTable = (typeof RESET_APPLICATION_TABLES)[number];
export type PreservedApplicationTable =
  (typeof PRESERVED_APPLICATION_TABLES)[number];
